### ISSUE TITLE
Key Error :masked_lm_labels 

### ISSUE THREAD

**Issue by hbatra21** [elephantmipt/bert-distillation#7]
KeyError                                  Traceback (most recent call last)
<ipython-input-38-af67e8572b73> in <module>
      7     verbose=True,
      8     num_epochs=10,  # epochs number
----> 9     callbacks=callbacks,
     10 )

/opt/conda/lib/python3.6/site-packages/catalyst/dl/runner/runner.py in train(self, model, criterion, optimizer, scheduler, datasets, loaders, callbacks, logdir, resume, num_epochs, valid_loader, main_metric, minimize_metric, verbose, stage_kwargs, checkpoint_data, fp16, distributed, check, timeit, load_best_on_end, initial_seed, state_kwargs)
    151         )
    152         self.experiment = experiment
--> 153         utils.distributed_cmd_run(self.run_experiment, distributed)
    154 
    155     def infer(

/opt/conda/lib/python3.6/site-packages/catalyst/utils/scripts.py in distributed_cmd_run(worker_fn, distributed, *args, **kwargs)
    128         or world_size <= 1
    129     ):
--> 130         worker_fn(*args, **kwargs)
    131     elif local_rank is not None:
    132         torch.cuda.set_device(int(local_rank))

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in run_experiment(self, experiment)
    932             if _exception_handler_check(getattr(self, "callbacks", None)):
    933                 self.exception = ex
--> 934                 self._run_event("on_exception")
    935             else:
    936                 raise ex

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in _run_event(self, event)
    744         """
    745         for callback in self.callbacks.values():
--> 746             getattr(callback, event)(self)
    747 
    748     def _batch2device(

/opt/conda/lib/python3.6/site-packages/catalyst/core/callbacks/exception.py in on_exception(self, runner)
     20 
     21         if runner.need_exception_reraise:
---> 22             raise exception

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in run_experiment(self, experiment)
    920         try:
    921             for stage in self.experiment.stages:
--> 922                 self._run_stage(stage)
    923         except (Exception, KeyboardInterrupt) as ex:
    924             from catalyst.core.callbacks.exception import ExceptionCallback

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in _run_stage(self, stage)
    896             )
    897             self._run_event("on_epoch_start")
--> 898             self._run_epoch(stage=stage, epoch=self.epoch)
    899             self._run_event("on_epoch_end")
    900 

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in _run_epoch(self, stage, epoch)
    875             self._run_event("on_loader_start")
    876             with torch.set_grad_enabled(self.is_train_loader):
--> 877                 self._run_loader(loader)
    878             self._run_event("on_loader_end")
    879 

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in _run_loader(self, loader)
    816             self.global_batch_step += 1
    817             self.loader_batch_step = i + 1
--> 818             self._run_batch(batch)
    819             if self.need_early_stop:
    820                 self.need_early_stop = False

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in _run_batch(self, batch)
    796         self._run_event("on_batch_start")
    797         self._handle_batch(batch=batch)
--> 798         self._run_event("on_batch_end")
    799 
    800     def _run_loader(self, loader: DataLoader) -> None:

/opt/conda/lib/python3.6/site-packages/catalyst/core/runner.py in _run_event(self, event)
    744         """
    745         for callback in self.callbacks.values():
--> 746             getattr(callback, event)(self)
    747 
    748     def _batch2device(

/opt/conda/lib/python3.6/site-packages/catalyst/core/callbacks/metrics.py in on_batch_end(self, runner)
     84     def on_batch_end(self, runner: IRunner) -> None:
     85         """Computes the metric and add it to batch metrics."""
---> 86         metric = self._compute_metric(runner) * self.multiplier
     87         runner.batch_metrics[self.prefix] = metric
     88 

/opt/conda/lib/python3.6/site-packages/catalyst/core/callbacks/metrics.py in _compute_metric_value(self, runner)
     70     def _compute_metric_value(self, runner: IRunner):
     71         output = self._get_output(runner.output, self.output_key)
---> 72         input = self._get_input(runner.input, self.input_key)
     73 
     74         metric = self.metric_fn(output, input, **self.metrics_kwargs)

/opt/conda/lib/python3.6/site-packages/catalyst/utils/dict.py in get_key_str(dictionary, key)
     16         value
     17     """
---> 18     return dictionary[key]
     19 
     20 

KeyError: 'masked_lm_labels'

While running the notebook API, I encountered this error. Please help me resolve this error. All I'm trying is text classification. 
PS: I could not find a solution on SO.

**Comment by hbatra21** [comment]
@elephantmipt What could be the possible reason for this error? While running the epochs.

**Comment by elephantmipt** [comment]
Hi! This problem is probably connected with the `transformers` version. Try to run  `pip install transformers==1.9` in your terminal and then run training again. Thank you for noticing this problem!
